# 1. What is Statistics?

Statistics is the process of collecting, organizing, analyzing, interpreting, and presenting data.

In simple words, statistics helps us understand a large amount of information by converting raw data into meaningful information.

For example, suppose we have the marks of 100 students.

Instead of looking at all 100 marks individually, statistics allows us to calculate:

- Average marks
- Highest marks
- Lowest marks
- Middle value
- How much the marks vary
- How the marks are distributed

Therefore, statistics helps us understand patterns and make decisions using data.

In [1]:
import numpy as np

marks = np.array([60, 70, 80, 90, 100])

average = np.mean(marks)
minimum = np.min(marks)
maximum = np.max(marks)

print("Marks:", marks)
print("Average:", average)
print("Minimum:", minimum)
print("Maximum:", maximum)

Marks: [ 60  70  80  90 100]
Average: 80.0
Minimum: 60
Maximum: 100


# 2. Why Statistics is Important in AI/ML

Machine learning works with data, and statistics provides tools to understand that data.

Statistics helps an AI/ML engineer to:

1. Understand the dataset
2. Find patterns in data
3. Identify unusual values
4. Measure relationships between variables
5. Summarize large datasets
6. Select useful features
7. Evaluate machine-learning models
8. Understand uncertainty in predictions

For example, before training a model, we may need to know:

- What is the average value?
- Are there missing values?
- Are there outliers?
- How are values distributed?
- Are two variables related?

Statistics provides methods to answer these questions.

In [2]:
import numpy as np

customers = np.array([1000])
churned = np.array([200])

churn_rate = (churned / customers) * 100

print("Total Customers:", customers[0])
print("Churned Customers:", churned[0])
print("Churn Rate:", churn_rate[0], "%")

Total Customers: 1000
Churned Customers: 200
Churn Rate: 20.0 %


20% of customers have churned.

This simple statistical measurement gives us useful information about the dataset before building a churn prediction model.

# 3. Statistics vs Machine Learning

Statistics and Machine Learning both work with data, but their main goals are different.

Statistics traditionally focuses on understanding data, relationships, uncertainty, and drawing conclusions about a population.

Machine Learning focuses mainly on learning patterns from data so that a model can make predictions or decisions on new data.

Statistics asks questions such as:

- What is the average?
- Is there a relationship between variables?
- How confident are we about our result?
- Can we make conclusions about a population?

Machine Learning asks questions such as:

- Can we predict house prices?
- Can we classify an image?
- Can we predict whether a customer will churn?
- Can we recognize spam emails?

Statistics is often used to understand and analyze data, while Machine Learning uses data to build models that can generalize to new observations.

The two fields overlap heavily.

In [3]:
import numpy as np

area = np.array([1000, 1200, 1500, 1800, 2000])
price = np.array([50, 60, 75, 90, 100])

correlation = np.corrcoef(area, price)[0, 1]

print("Correlation between area and price:", correlation)

Correlation between area and price: 1.0


# 4. Descriptive Statistics

Descriptive statistics describes or summarizes the data that we already have.

It does not try to make predictions about a larger population.

Common descriptive statistics include:

- Mean
- Median
- Mode
- Minimum
- Maximum
- Range
- Variance
- Standard deviation
- Percentiles

For example, if we have the marks of 100 students, descriptive statistics can summarize those 100 marks.

In [4]:
import numpy as np

marks = np.array([60, 70, 70, 80, 90])

print("Mean:", np.mean(marks))
print("Median:", np.median(marks))
print("Minimum:", np.min(marks))
print("Maximum:", np.max(marks))
print("Standard Deviation:", np.std(marks))

Mean: 74.0
Median: 70.0
Minimum: 60
Maximum: 90
Standard Deviation: 10.198039027185569


# 5. Inferential Statistics

Inferential statistics uses information from a sample to make conclusions or estimates about a larger population.

For example, suppose a university has 10,000 students.

It may be difficult to ask every student about their satisfaction.

Instead, we can select 500 students and collect their responses.

We can use the sample results to estimate the satisfaction level of the entire student population.

Inferential statistics commonly involves:

- Sampling
- Estimation
- Confidence intervals
- Hypothesis testing
- Statistical tests

In [5]:
import numpy as np

sample = np.array([1, 1, 0, 1, 0, 1, 1, 0, 1, 1])

satisfaction_rate = np.mean(sample) * 100

print("Sample Satisfaction Rate:", satisfaction_rate, "%")

Sample Satisfaction Rate: 70.0 %


# 6. Population

A population is the complete group of individuals or objects that we are interested in studying.

Examples:

- All customers of a company
- All students in a university
- All houses in a city
- All transactions made by a bank

The population can be very large.

When studying a population, collecting information from every member may be expensive or time-consuming.

In [6]:
import numpy as np

population = np.array([100, 200, 300, 400, 500])

population_mean = np.mean(population)

print("Population:", population)
print("Population Mean:", population_mean)

Population: [100 200 300 400 500]
Population Mean: 300.0


# 7. Sample

A sample is a smaller subset selected from a population.

Instead of studying every member of a population, we select some members and study them.

For example:

Population = 100,000 customers

Sample = 1,000 customers

The sample should ideally represent the population reasonably well.

In [7]:
import numpy as np

population = np.arange(1, 101)

sample = np.random.choice(population, size=10, replace=False)

print("Population:", population)
print("Sample:", sample)

Population: [  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]
Sample: [36 77 28 85 20 48  7 89 92 67]


# 8. Census

A census means collecting information from every member of the population.

For example, if a company has 1,000 employees and collects salary information from all 1,000 employees, it is conducting a census.

Census provides information about the entire population, but it can require more:

- Time
- Money
- Resources

In [8]:
import numpy as np

population = np.array([25000, 30000, 35000, 40000, 45000])

census_mean = np.mean(population)

print("All Employee Salaries:", population)
print("Census Mean Salary:", census_mean)

All Employee Salaries: [25000 30000 35000 40000 45000]
Census Mean Salary: 35000.0


# 9. Sampling

Sampling is the process of selecting a subset of observations from a population.

Sampling is useful when studying the entire population is difficult, expensive, or time-consuming.

Examples of sampling methods include:

- Random sampling
- Systematic sampling
- Stratified sampling
- Cluster sampling

A good sampling method helps produce a sample that represents the population.

In [9]:
import numpy as np

population = np.arange(1, 10001)

sample = np.random.choice(
    population,
    size=500,
    replace=False
)

print("Population Size:", len(population))
print("Sample Size:", len(sample))
print("First 10 Sample Values:", sample[:10])

Population Size: 10000
Sample Size: 500
First 10 Sample Values: [2431 2291 7201 2502 1242 3127 3995  250  899 3234]


# 10. Variables

A variable is a characteristic or property that can have different values for different observations.

Examples:

- Age
- Salary
- Gender
- Height
- Number of products
- City

For example, if we have student data:

Student A → Age = 20
Student B → Age = 22
Student C → Age = 21

Age is a variable because its value changes between observations.

In [10]:
import pandas as pd

data = pd.DataFrame({
    "Age": [20, 21, 22],
    "Marks": [80, 75, 90]
})

print(data)

   Age  Marks
0   20     80
1   21     75
2   22     90


# 11. Features

A feature is an input variable used by a machine-learning model to learn patterns and make predictions.

For example, if we want to predict house price, possible features are:

- Area
- Number of bedrooms
- Location
- Age of house

The target is the value we want to predict.

Example:

Features → Area, Bedrooms, Age
Target → Price

In [11]:
import pandas as pd

data = pd.DataFrame({
    "Area": [1000, 1500, 2000],
    "Bedrooms": [2, 3, 4],
    "Age": [10, 5, 3],
    "Price": [50, 75, 100]
})

X = data[["Area", "Bedrooms", "Age"]]
y = data["Price"]

print("Features:")
print(X)

print("\nTarget:")
print(y)

Features:
   Area  Bedrooms  Age
0  1000         2   10
1  1500         3    5
2  2000         4    3

Target:
0     50
1     75
2    100
Name: Price, dtype: int64


# 12. Observation

An observation is one individual record or data point in a dataset.

Usually, a row represents one observation.

For example:

| Age | Salary | Experience |
|---:|---:|---:|
| 25 | 30000 | 2 |
| 30 | 50000 | 5 |
| 35 | 70000 | 8 |

Each row is one observation.

Therefore:

Number of observations = Number of rows

In [12]:
import pandas as pd

data = pd.DataFrame({
    "Age": [25, 30, 35],
    "Salary": [30000, 50000, 70000],
    "Experience": [2, 5, 8]
})

print("Number of observations:", len(data))
print("\nFirst observation:")
print(data.iloc[0])

Number of observations: 3

First observation:
Age              25
Salary        30000
Experience        2
Name: 0, dtype: int64


# 13. Dataset

A dataset is a structured collection of data containing observations and variables.

In a tabular dataset:

- Rows usually represent observations.
- Columns usually represent variables/features.

Example:

| Age | Salary | Experience |
|---:|---:|---:|
| 25 | 30000 | 2 |
| 30 | 50000 | 5 |
| 35 | 70000 | 8 |

This dataset contains:

3 observations

and

3 variables.

In [13]:
import pandas as pd

dataset = pd.DataFrame({
    "Age": [25, 30, 35],
    "Salary": [30000, 50000, 70000],
    "Experience": [2, 5, 8]
})

print(dataset)

print("\nRows:", dataset.shape[0])
print("Columns:", dataset.shape[1])

   Age  Salary  Experience
0   25   30000           2
1   30   50000           5
2   35   70000           8

Rows: 3
Columns: 3


# 14. Quantitative Data

Quantitative data represents information that can be expressed using numbers.

Examples:

- Age
- Salary
- Height
- Weight
- Number of customers
- Temperature

Quantitative data can usually be used in mathematical calculations.

There are two important types:

1. Discrete data
2. Continuous data

In [14]:
import numpy as np

ages = np.array([20, 25, 30, 35, 40])

print("Average Age:", np.mean(ages))
print("Maximum Age:", np.max(ages))

Average Age: 30.0
Maximum Age: 40


# 15. Qualitative Data

Qualitative data describes categories or qualities rather than numerical measurements.

Examples:

- Gender
- City
- Product category
- Color
- Department
- Payment method

For example:

City:

Chennai
Coimbatore
Bangalore
Mumbai

These values represent categories rather than numerical measurements.

In [15]:
import pandas as pd

payment_methods = pd.Series([
    "UPI",
    "Credit Card",
    "UPI",
    "Cash",
    "Debit Card"
])

print(payment_methods)

print("\nFrequency:")
print(payment_methods.value_counts())

0            UPI
1    Credit Card
2            UPI
3           Cash
4     Debit Card
dtype: object

Frequency:
UPI            2
Credit Card    1
Cash           1
Debit Card     1
Name: count, dtype: int64


# 16. Continuous Data

Continuous data can take any value within a range.

It is usually obtained through measurement.

Examples:

- Height
- Weight
- Temperature
- Distance
- Time

For example, height can be:

170 cm
170.2 cm
170.25 cm
170.257 cm

There can theoretically be many possible values between two points.

In [16]:
import numpy as np

temperature = np.array([
    25.1,
    25.5,
    26.2,
    27.8,
    28.4
])

print("Average Temperature:", np.mean(temperature))
print("Minimum Temperature:", np.min(temperature))
print("Maximum Temperature:", np.max(temperature))

Average Temperature: 26.6
Minimum Temperature: 25.1
Maximum Temperature: 28.4


# 17. Discrete Data

Discrete data consists of separate, countable values.

It usually represents something that can be counted.

Examples:

- Number of children
- Number of products
- Number of employees
- Number of orders
- Number of website visits

For example, the number of products can be:

1
2
3
4

But normally we would not say:

2.57 products.

In [17]:
import numpy as np

orders = np.array([1, 2, 3, 4, 5])

print("Average Orders:", np.mean(orders))
print("Total Orders:", np.sum(orders))

Average Orders: 3.0
Total Orders: 15


# 18. Structured Data

Structured data is data organized in a predefined format, usually rows and columns.

A relational database table is a common example.

Example:

| CustomerID | Age | Salary |
|---|---:|---:|
| C001 | 25 | 30000 |
| C002 | 30 | 50000 |
| C003 | 35 | 70000 |

The structure makes it easy for computers to store, query, analyze, and process the data.

Common examples include:

- SQL tables
- Excel spreadsheets
- CSV files
- Relational databases

In [18]:
import pandas as pd

data = pd.DataFrame({
    "CustomerID": ["C001", "C002", "C003"],
    "Age": [25, 30, 35],
    "Salary": [30000, 50000, 70000]
})

print(data)

  CustomerID  Age  Salary
0       C001   25   30000
1       C002   30   50000
2       C003   35   70000


# 19. Unstructured Data

Unstructured data does not follow a fixed tabular structure.

Examples include:

- Images
- Videos
- Audio
- Emails
- Documents
- Social media text

For example, an image does not naturally contain rows and columns like a database table.

However, machine-learning models can convert unstructured data into useful numerical representations.

In [19]:
import numpy as np

image = np.random.randint(
    0,
    256,
    size=(3, 3)
)

print("Image representation:")
print(image)

print("\nImage shape:", image.shape)

Image representation:
[[163 110 151]
 [152 231  57]
 [187 244  24]]

Image shape: (3, 3)
